services:
  backend:
    container_name: mflix-backend
    image: mflix
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: mflix-database
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: 888888
      POSTGRES_DB: mflix
    volumes:
      - mflix:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mflix:
